### ISSUE TITLE
前后端连接后不能正常通讯

### ISSUE THREAD

**Issue by jianpanxia233** [yangrc1234/Gomoku-Zero#1]
pycharm端报错 RuntimeError: There is no current event loop in thread 'Thread-x'.

**Comment by yangrc1234** [comment]
能否贴上详细的报错信息（包括栈信息），以及python的版本。  
推测是因为python版本的问题，如果不是3.6的python建议先安装一个3.6的python试试。

**Comment by jianpanxia233** [comment]
我按照您的建议安装了python3.6，仍然报错，运行playwithme.py这个文件可以玩，但在chrome浏览器上会报错500，在后端报错是这样的：
[2019-06-02 13:24:27,593] ERROR in app: Exception on /aiplay [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python36\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python36\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "C:\Python36\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 39, in aiplay
    status, move = aiRunner.aiplay()
  File "D:\python学习\Finalwuziqi\Finalwuziqi\aiclass.py", line 44, in aiplay
    move,policy_ = self.mcts.search_move(autoMoveIntoChild = False)
  File "D:\python学习\Finalwuziqi\Finalwuziqi\mcts.py", line 66, in search_move
    self.loop.run_until_complete(asyncio.gather(*coroutineList))
  File "C:\Python36\lib\asyncio\tasks.py", line 596, in gather
    fut = ensure_future(arg, loop=loop)
  File "C:\Python36\lib\asyncio\tasks.py", line 518, in ensure_future
    loop = events.get_event_loop()
  File "C:\Python36\lib\asyncio\events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "C:\Python36\lib\asyncio\events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-8'.
感谢您的任何建议

**Comment by yangrc1234** [comment]
抱歉，这个repo的部分代码并不是我写的，我个人对python的熟悉程度不高，可能无法解决你的问题。  
根据：https://stackoverflow.com/questions/46727787/runtimeerror-there-is-no-current-event-loop-in-thread-in-async-apscheduler，
试试把mcts.py的__init__函数里的
```
        self.loop = asyncio.get_event_loop()
```
修改为
```
        self.loop = asyncio.new_event_loop()  
        asyncio.set_event_loop(loop)
```
